MOUSEKEY_ENABLE  = no  # mouse keys
EXTRAKEY_ENABLE  = yes # audio control and system control
CONSOLE_ENABLE   = no  # console for debug
COMMAND_ENABLE   = no  # commands for debug and configuration
BACKLIGHT_ENABLE = no  # enable keyboard backlight functionality
MIDI_ENABLE      = no  # midi controls
AUDIO_ENABLE     = no  # audio output on port c6
BLUETOOTH_ENABLE = no  # enable bluetooth with the adafruit ez-key hid

ifndef QUANTUM_DIR
	include ../../../../Makefile
endif
