#!/usr/bin/env bash

chunkc=$HOME/Documents/Code/Utils/chunkwm/src/chunkc/bin/chunkc

$chunkc set global_desktop_mode          bsp

$chunkc set bsp_spawn_left               0
$chunkc set bsp_optimal_ratio            1.605

$chunkc set mouse_follows_focus          0
$chunkc set window_float_next            0
$chunkc set window_float_center          0
$chunkc set window_region_locked         1

$chunkc set global_desktop_offset_top    12
$chunkc set global_desktop_offset_bottom 12
$chunkc set global_desktop_offset_left   12
$chunkc set global_desktop_offset_right  12
$chunkc set global_desktop_offset_gap    12

# $chunkc set focused_border_color         0xC88F8F8F
# $chunkc set focused_border_width         4
# $chunkc set focused_border_radius        4

$chunkc core::plugin_dir ~/.chunkwm_plugins
$chunkc core::hotload 0
$chunkc core::load tiling.so
# $chunkc core::load border.so

# rules

$chunkc tiling::rule --owner AppCleaner --state float
$chunkc tiling::rule --owner Finder --name Copy --state float
$chunkc tiling::rule --owner Finder --name Move --state float
$chunkc tiling::rule --owner Reminders --state float
$chunkc tiling::rule --owner Simulator --state float
$chunkc tiling::rule --owner Transmission --state float
$chunkc tiling::rule --owner Tweetbot --state float
$chunkc tiling::rule --owner \"Archive Utility\" --state float
$chunkc tiling::rule --owner \"GIF Brewery 3\" --state float
$chunkc tiling::rule --owner \"Messages\" --state float
$chunkc tiling::rule --owner \"Photo Booth\" --state float
$chunkc tiling::rule --owner \"The Unarchiver\" --state float
$chunkc tiling::rule --owner iBooks --state float
$chunkc tiling::rule --owner iTunes --name \"Mini Player\" --state float
