if has("gui_macvim")
	" gui vim has light background by default
	set background=light

	" no bells
	set vb t_vb=

	" disable scrollbar
	set guioptions-=r
	set go-=L

	" enable native tabs
	set guioptions+=e

	" always show tabs
	set showtabline=2

	" font
	set guifont=Menlo:h11

	" turn off blinking cursor
	set gcr=n:blinkon0

	" default window size
	set lines=72 columns=150

	" disable printing from menu
	macmenu &File.Print key=<nop>

	" comment lines with cmd-/
	map <D-/> :TComment<cr>
	vmap <D-/> :TComment<cr>gv

	" change tabs with ctrl-tab
	noremap <C-Tab> :tabnext<cr>
	noremap <C-S-Tab> :tabprev<cr>

	" fullscreen switching command
	function! FullScreen()
		set fullscreen!

		if &fullscreen
			set guioptions-=e
		else
			set guioptions+=e
		endif
	endfun

	command! FullScreen :call FullScreen()

	" open terminal in current directory
	function! Terminal()
		execute "silent !" . "open -a Terminal " . getcwd()
	endfun

	command! Terminal :call Terminal()

endif
