" no bells
set vb t_vb=

" disable scrollbar
set guioptions-=r
set go-=L

" enable native tabs
" set guioptions+=e

" always show tabs
" set showtabline=2

" font
set guifont=Menlo:h11

" turn off blinking cursor
set gcr=n:blinkon0

" default window size
set lines=64 columns=132

" disable printing from menu
macmenu &File.Print key=<nop>
