files=(
  options
  path
  terminfo
  completion
  colors
  vim
  prompt
  plugins
  locale
  exports
  aliases
  functions
  fzf
  history
  bindkeys
  terminal
  autopair
  docker
  # locale
  # rbenv
)

for file in $files; do
  source ~/.zsh/$file.zsh
done

if [ "$(uname)" = "Darwin" ]; then
  source ~/.zsh/nvm.zsh;
  source ~/.zsh/darwin.zsh;
fi

if [ "$(uname)" = "Linux" ]; then
  source ~/.zsh/linux.zsh;
fi

if [ -d ~/Documents/Dropbox/Notes ]; then
  source ~/.zsh/notes.zsh
fi

if [ -d /usr/local/opt/nvm/ ]; then
  source ~/.zsh/nvm.zsh
fi
