if [ -f ~/.zsh/plugins/zsh-defer/zsh-defer.plugin.zsh ]; then
  source ~/.zsh/plugins/zsh-defer/zsh-defer.plugin.zsh
else
  echo "zsh-defer is missing! run \`zsh_plugin_install\`"
  echo "you'll get some errors below..."
  echo
fi

# load files
files=(
  options
  terminfo
  completion
  vim
  locale
  muninn
  aliases
  functions
  history
  bindkeys
  terminal
  reporttime
  fzf
  colors
  prompt
  plugins
)

if [ "$(uname)" = "Darwin" ]; then
  source ~/.zsh/darwin.zsh
else
  source ~/.zsh/linux.zsh
fi

for file in $files; do
  source ~/.zsh/$file.zsh
done

