# load files
files=(
  options
  path
  terminfo
  colors
  completion
  vim
  locale
  exports
  aliases
  functions
  history
  bindkeys
  terminal
  reporttime
  direnv
  plugins
  prompt
  fzf
)

if [ "$(uname)" = "Darwin" ]; then
  source ~/.zsh/darwin.zsh
elif [ "$(uname)" = "Linux" ]; then
  source ~/.zsh/linux.zsh;
fi

for file in $files; do
  source ~/.zsh/$file.zsh
done

