AUDIO_ENABLE     = no  # audio output on port c6
BACKLIGHT_ENABLE = no  # enable keyboard backlight functionality
BLUETOOTH_ENABLE = no  # enable bluetooth with the adafruit ez-key hid
COMMAND_ENABLE   = no  # commands for debug and configuration
CONSOLE_ENABLE   = no  # console for debug
EXTRAKEY_ENABLE  = yes # audio control and system control
MIDI_ENABLE      = no  # midi controls
MOUSEKEY_ENABLE  = no  # mouse keys
TAP_DANCE_ENABLE = no  # tap dance

ifndef QUANTUM_DIR
	include ../../../../Makefile
endif
