#!/usr/bin/env bash

# ignore the stupid splashscreen if we have HammerSpoon
if [ -e /usr/local/bin/hs ]; then
  PREV_WINDOW_ID=$(/usr/local/bin/hs -c "hs.window.focusedWindow():id()")
  (sleep 0.5 && /usr/local/bin/hs -c "hs.window.find($PREV_WINDOW_ID):raise():focus()") > /dev/null &
fi

/Applications/Arduino.app/Contents/MacOS/Arduino "$@"

# This compiles but doesn't upload...
#
# /Applications/Arduino.app/Contents/Java/arduino-builder \
#   -compile \
#   -verbose \
#   -hardware /Applications/Arduino.app/Contents/Java/hardware \
#   -hardware "$HOME"/Documents/Code/Arduino/hardware \
#   -tools /Applications/Arduino.app/Contents/Java/tools-builder \
#   -tools /Applications/Arduino.app/Contents/Java/hardware/tools \
#   -libraries "$HOME"/Documents/Code/Arduino/libraries \
#   -fqbn "arduino:avr:uno" \
#   "$1"
