#!/usr/bin/env node
// simple script for counting "worked hours", used only in vim

var stdin = process.openStdin();
var data  = '';

var timeLineRegex = /(\d{2}:\d{2})\ \-\ (\d{2}:\d{2})/;

var converToMinutes = function(timeStr) {
  return parseInt(timeStr.split(':')[0]) * 60 + parseInt(timeStr.split(':')[1]);
};

var calculateTime = function(line) {
  var matches = line.match(timeLineRegex);

  var from = converToMinutes(matches[1]);
  var to   = converToMinutes(matches[2]);

  return to - from;
};

stdin.on('data', function(chunk) { data += chunk; });

stdin.on('end', function() {
  var total = 0;

  var counted = data.split('\n')
    .filter(function(line) {
      return line.length > 1;
    })
    .reduce(function(memo, line) {
      if (!line.match(timeLineRegex)) {
        memo.push({
          project: line,
          time:    0
        });
      }
      else {
        var time = calculateTime(line);

        memo[memo.length - 1].time += time;
        total += time;
      }

      return memo;
    }, [])
    .map(function(result) {
      return result.project + ': ' + (result.time / 60).toFixed(1) + 'h';
    });

  var resultStr = counted.join(', ');

  if (counted.length > 1) {
    resultStr += ', Total: ' + (total / 60).toFixed(1) + 'h';
  }

  console.log(resultStr);
});
