#!/usr/bin/env bash

# set ffmpeg options
case $1 in
	ipad|iPad)
		OPTIONS="-acodec libfaac -ac 2 -ab 160k -s 1024x768 -vcodec libx264 -vpre iPod640 -b 1200k"
		EXT=".iPad.mp4"
		;;
	mjpeg)
		OPTIONS="-vcodec mjpeg -qscale 1 -an"
		EXT=".MJPEG.avi"
		;;
	h264)
		OPTIONS="-qscale 1 -vcodec libx264"
		EXT=".H264.mp4"
		;;
	mp3)
		OPTIONS="-f mp3 -acodec libmp3lame -ab 320000 -ar 44100"
		EXT=".mp3"
		;;
	*)
		echo "Usage: $0 [preset] [files]"
		;;
esac

# remove first attribute given from command line
shift

# convert files
for f in "$@"
do
	ffmpeg -threads 0 -i "${f}" $OPTIONS "${f%.*}$EXT"
done
