#!/usr/bin/env bash

if [ -z "$1" ]; then
  echo "Trigger ifttt maker channel"
  echo
  echo "  ifttt-trigger maker_channel_trigger message"
  echo
  exit 0
fi

# get $TOKEN
source ~/.iftttrc

TRIGGER="$1"
MESSAGE="$2"

curl \
  -s \
  -X POST \
  --data "value1=$MESSAGE" \
  "https://maker.ifttt.com/trigger/$TRIGGER/with/key/$TOKEN" > /dev/null

echo "triggered $TRIGGER with value \"$MESSAGE\""

