#!/usr/bin/env bash

# get $TOKEN
source ~/.iftttrc

TRIGGER="notify"
MESSAGE="$@"

curl \
  -s \
  -X POST \
  --data "value1=$MESSAGE" \
  "https://maker.ifttt.com/trigger/$TRIGGER/with/key/$TOKEN" > /dev/null
