#!/usr/bin/env bash

ix() {
  if [ -t 0 ]; then
    local filename="$*"

    if [ "$filename" ]; then
      curl -F 'f:1=<-' http://ix.io < "$filename"
      return
    else
      echo "Nothing to do, exiting."
    fi
  else
    curl -F 'f:1=<-' http://ix.io
  fi
}

ix "$*"
