#!/usr/bin/env bash

paths=(
  ~/Documents/Projects
  ~/Documents/Work
  ~/Documents/Work/Archive
  ~/Documents/Code
  ~/Documents/Talks
  ~/Documents/Teaching
)

list_projects() {
  ls -1 "${paths[@]}" | grep -v Archive | sed -E "/^.*:$|^$/d" | sort
}

open_project() {
  project="$*"

  for path in ${paths[*]}; do
    if [ -d "$path/$project" ]; then
      pushd "$path/$project" > /dev/null || return
      tm
      popd > /dev/null || return
      break
    fi
  done
}

choose() {
  local project

  project=$(list_projects | fzf --prompt="project > " --reverse)

  if [[ -z "$project" ]]; then
    exit 0
  fi

  open_project "$project"
}

usage() {
  echo "Manage projects, usage:"
  echo
  echo "  p project               open existing project"
  echo "  p --ls                  list all projects"
  echo
  exit 0
}

main() {
  if [ -z "$1" ]; then
    choose
    return
  fi

  case "$1" in
    "--list"|"--ls")
      list_projects
      ;;
    "--help"|"-h")
      usage
      ;;
    *)
      open_project "$@"
      ;;
  esac
  shift
}

main "$@"
