#!/usr/bin/env bash

PLASK="/Users/Szymon/Documents/Code/Utils/Plask/build/Release/Plask.app/Contents/MacOS/Plask"
MULTI=false

while [ $# -gt 0 ]; do
  opt=$1
  shift

  case ${opt} in
    --multi)
      MULTI=true
      ;;
    *)
      argv+=(${opt})
      ;;
  esac
done

if [[ ${MULTI} ]]; then
  killall Plask > /dev/null 2>&1
fi

$PLASK ${argv[0]}
