#!/usr/bin/env bash
# script to launch processing apps from command line


if [ "$#" -ne 0 ]; then
  if [[ -d "$@" ]]; then
    DIR="$@"
  elif [[ -f "$@" ]]; then
    DIR=$(dirname "$@")
  fi
else
  DIR="$(pwd)"
fi

if [ ! "${DIR:0:1}" = "/" ]; then
  DIR=$(pwd)"/"$DIR
fi

cd "/Applications/Processing.app/Contents/Java" && /Applications/Processing.app/Contents/PlugIns/jdk1.7.0_55.jdk/Contents/Home/jre/bin/java -cp "pde.jar:antlr.jar:jna.jar:ant.jar:ant-launcher.jar:org-netbeans-swing-outline.jar:com.ibm.icu_4.4.2.v20110823.jar:jdi.jar:jdimodel.jar:org.eclipse.osgi_3.8.1.v20120830-144521.jar:core/library/core.jar" processing.mode.java.Commander --output=/var/tmp/Processing --force --run --sketch="$DIR"
