#!/usr/bin/env bash
# script to launch processing apps from command line

DIR="$(pwd)"

cd "/Applications/Processing.app/Contents/Resources/Java" && /usr/libexec/java_home --request --version 1.6 --exec java -cp lib/pde.jar:lib/antlr.jar:lib/jna.jar:lib/ant.jar:lib/ant-launcher.jar:lib/org-netbeans-swing-outline.jar:lib/com.ibm.icu_4.4.2.v20110823.jar:lib/jdi.jar:lib/jdimodel.jar:lib/org.eclipse.osgi_3.8.1.v20120830-144521.jar:core/library/core.jar processing.mode.java.Commander --output=/var/tmp/Processing --force --run --sketch="$DIR/$@"
