#!/usr/bin/env bash

# get $TOKEN and $USER
source ~/.pushoverrc

case $1 in
  -h|--high)
    PRIORITY="1"
    shift
    ;;
  *)
    PRIORITY="0"
    ;;
esac

MESSAGE="notification!"
if [ "$#" -ne 0 ]; then
  MESSAGE="$*"
fi

curl \
  -s \
  -F "priority=$PRIORITY" \
  -F "token=$TOKEN" \
  -F "user=$USER" \
  -F "message=$MESSAGE" \
  https://api.pushover.net/1/messages > /dev/null
