#!/usr/bin/env bash
# mostly stolen from: https://github.com/mathiasbynens/dotfiles/blob/master/.osx

# set the icon size of Dock items to 48 pixels
defaults write com.apple.dock tilesize -int 48

# lock Dock size
defaults write com.apple.dock size-immutable -bool yes

# disable local Time Machine backups
hash tmutil &> /dev/null && sudo tmutil disablelocal

# disable Sudden Motion Sensor (default - 1)
sudo pmset -a sms 0 &> /dev/null

# decrese standby delay to 20 minutes
sudo pmset -a standbydelay 1200

# enable locate command
sudo launchctl load -w /System/Library/LaunchDaemons/com.apple.locate.plist > /dev/null 2>&1

# enable trim 10.10.4+
read -p "Enble trim? (y/n) " RESP
if [ "$RESP" = "y" ]; then
  sudo trimforce enable
fi

# kill affected apps
for app in "Dock" "Finder" "SystemUIServer"
do
  killall "$app" > /dev/null 2>&1
done
echo "$(tput setaf 1)Done. Note that some of these changes require a logout/restart to take effect.$(tput sgr0)"
