#!/usr/bin/env bash

# mostly stolen from: https://github.com/mathiasbynens/dotfiles/blob/master/.macos

# disable new window animation
defaults write NSGlobalDomain NSAutomaticWindowAnimationsEnabled -bool false

# disable focus ring animation
defaults write NSGlobalDomain NSUseAnimatedFocusRing -bool false

# increase window resize speed
defaults write NSGlobalDomain NSWindowResizeTime -float 0.001

# set the icon size of Dock items
defaults write com.apple.dock tilesize -int 40

# lock Dock size
defaults write com.apple.dock size-immutable -bool true

# expand save panel by default
defaults write NSGlobalDomain NSNavPanelExpandedStateForSaveMode -bool true
defaults write NSGlobalDomain NSNavPanelExpandedStateForSaveMode2 -bool true

# expand print panel by default
defaults write NSGlobalDomain PMPrintingExpandedStateForPrint -bool true
defaults write NSGlobalDomain PMPrintingExpandedStateForPrint2 -bool true

# save to disk (not to iCloud) by default
defaults write NSGlobalDomain NSDocumentSaveNewDocumentsToCloud -bool false

# save screenshots to Dropbox
defaults write com.apple.screencapture location ~/Documents/Dropbox/Screenshots/

# disable Sudden Motion Sensor (default - 1)
sudo pmset -a sms 0 &> /dev/null

echo "$(tput setaf 1)done, note that some of these changes require app restart or logout to take effect...$(tput sgr0)"
