#!/usr/bin/env bash

# remount everything on wake
/usr/sbin/diskutil list | awk '/Apple_HFS/ {print $NF}' | xargs -I{} /usr/sbin/diskutil mount {} > /dev/null 2>&1 &

# check if docked - DELL monitor is connected
sleep 0.1s
DELLCOUNT=$(/usr/sbin/system_profiler SPDisplaysDataType | grep -i dell | wc -l)

if [[ $DELLCOUNT -eq 1 ]]; then
	# docked state: bluetooth on, ethernet location
	/usr/local/bin/blueutil power 1 > /dev/null 2>&1 &
	/usr/sbin/scselect Ethernet > /dev/null 2>&1 &
else
	# undocked state: bluetooth off, wireless location
	/usr/local/bin/blueutil power 0 > /dev/null 2>&1 &
	/usr/sbin/scselect Wireless > /dev/null 2>&1 &
fi
