#!/usr/bin/env bash
# simple single line system statistics

UPTIME="$(uptime)"

UP=$(echo "$UPTIME" | \
awk '{
  sub(/.*up[ ]+/,"",$0)
  sub(/,[ ]+[0-9]+ user.*/,"",$0)
  sub(/,/,"",$0)
  print($0)
}')
MSG="uptime: $(tput setaf 4)$UP$(tput sgr0)"

# PS=$(ps h -d | wc -l)
# MSG="$MSG, processes: $(tput setaf 1)$PS$(tput sgr0)"

LOAD=$(echo "$UPTIME" | sed 's/.*load average: //' | awk -F\, '{print $2}')
MSG="$MSG, load:$(tput setaf 5)$LOAD$(tput sgr0)"

if hash screen 2> /dev/null; then
  SCREEN=$(screen -ls | egrep '\(*\)' | wc -l)
  if [ "$SCREEN" != "0" ]; then
    MSG="$MSG, screens: $(tput setaf 2)$SCREEN$(tput sgr0)"
  fi
fi

if hash tmux 2> /dev/null; then
  TMUX=$(tmux ls 2> /dev/null | grep -c window)
  if [ "$TMUX" != "0" ]; then
    MSG="$MSG, tmuxes: $(tput setaf 2)$TMUX$(tput sgr0)"
  fi
fi

if [ "$(uname)" = "Darwin" ]; then
  BATTERY_CHARGE=$(pmset -g ps | sed -n 's/.*[[:blank:]]+*\(.*%\).*/\1/p')

  BATTERY_MAX=$(ioreg -w0 -l | grep MaxCapacity | cut -d '=' -f2)
  BATTERY_DESIGN=$(ioreg -w0 -l | grep DesignCapacity | cut -d '=' -f2)
  BATTERY_HEALTH=$(echo "scale=2; $BATTERY_MAX / $BATTERY_DESIGN * 100" | bc | sed "s/\..*//g")

  if [ "$BATTERY" != "100%" ]; then
    MSG="$MSG, battery charge: $(tput setaf 3)$BATTERY_CHARGE$(tput sgr0)"
    MSG="$MSG, battery health: $(tput setaf 3)$BATTERY_HEALTH%$(tput sgr0)"
  fi
fi

echo "$MSG"
