#!/usr/bin/env bash

source ~/.iftttrc

today() {
  icalBuddy -ea -b '- ' -ic 'Tracking' eventsToday \
    | grep '^-\ ' -C1 \
    | grep -v '\-\-' \
    | grep -v 'notes:' \
    | grep -v 'attendees:' \
    | grep -v 'location:' \
    | uniq \
    | awk '!(NR%2){print$0" "p}{p=$0}' \
    | cut -d ' ' -f5- \
    | sed 's/ (Tracking)//'
}

now() {
  icalBuddy -ea -b '- ' -ic 'Tracking' eventsNow \
    | grep '^-\ ' -C1 \
    | cut -d ' ' -f2- \
    | sed 's/ (Tracking)//' \
    | head -1
}

gcalcli-add() {
  gcalcli quick --calendar 'Tracking' "$2"
}

gcal-add() {
  # using ifttt applet: webhook with event name = $TRIGGER to Quick add event in google calendar, quick add text is {{value1}}

  TRIGGER="google_calendar_quickadd"

  curl -X POST -H "Content-Type: application/json" -d "{\"value1\":\"$2 $3-$4\"}" "https://maker.ifttt.com/trigger/$TRIGGER/with/key/$TOKEN" > /dev/null 2>&1
}

ical-add() {
  # slow...

  osascript - "$2" "$3" "$4" << END
on run argv
  set calendarName to "Tracking"
  set theSummary to item 1 of argv
  set startDate to item 2 of argv
  set endDate to item 3 of argv

  set startDate to date startDate
  set endDate to date endDate

  tell application "Calendar"
    tell (first calendar whose name is calendarName)
      make new event at end of events with properties {summary:theSummary, start date:startDate, end date:endDate}
    end tell
  end tell
end run
END
}

ical-mark() {
  # slow...

  osascript - "$2" "$3" << END
on run argv
  set calendarName to "Tracking"
  set theSummary to item 1 of argv
  set theDescription to item 2 of argv
  set startDate to (current date)

  tell application "Calendar"
    tell (first calendar whose name is calendarName)
      make new event at end of events with properties {summary:theSummary, start date:startDate, description:theDescription, allday event:true}
    end tell
  end tell
end run
END
}

usage() {
  echo "Easily create tracking info, usage:"
  echo
  echo "  track list"
  echo "  track now"
  echo "  track add 'Workflow @personal @work @language(osascript) 16:00-17:00'"
  echo
  exit 0
}

main() {
  if [ -z "$1" ]; then
    usage
  fi

  case "$1" in
    "today" | "list")
      today
      ;;
    "now")
      now
      ;;
    "add")
      gcalcli-add "$@" > /dev/null &
      ;;
    --help | -help | -h)
      usage
      ;;
    *)
      usage
      ;;
  esac
  shift
}

main "$@"
